# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 02:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11, '手机号只有11个字符')])),
                ('user_name', models.CharField(max_length=16, null=True, validators=[django.core.validators.MinLengthValidator(4, '昵称最少有4个字符')])),
                ('password', models.CharField(max_length=32)),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女'), (3, '保密')], default=3)),
                ('school', models.CharField(max_length=100, null=True)),
                ('hometown', models.CharField(max_length=100, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
