# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-27 13:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='收货人姓名')),
                ('telephone', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11, '手机号长度不正确'), django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '手机号码格式不正确')], verbose_name='手机号码')),
                ('province', models.CharField(max_length=50, verbose_name='省份')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('area', models.CharField(max_length=50, verbose_name='地区')),
                ('brief', models.CharField(max_length=50, verbose_name='详细地址')),
                ('is_difault', models.BooleanField(default=False, verbose_name='默认地址')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11, '手机号长度不正确'), django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '手机号码格式不正确')], verbose_name='手机号码')),
                ('user_name', models.CharField(max_length=16, null=True, validators=[django.core.validators.MinLengthValidator(4, '昵称最少有4个字符')], verbose_name='昵称')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女'), (3, '保密')], default=3, verbose_name='性别')),
                ('birthday', models.DateField(null=True, verbose_name='生日')),
                ('school', models.CharField(max_length=100, null=True, verbose_name='学校')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='详细地址')),
                ('hometown', models.CharField(max_length=100, null=True, verbose_name='老家')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('head', models.ImageField(default='head/memtx.png', upload_to='head/%Y%m')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='harvestaddress',
            name='add_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Users', verbose_name='用户id'),
        ),
    ]
