# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-21 11:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='收货人姓名')),
                ('telephone', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11, '手机号长度不正确'), django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '手机号码格式不正确')], verbose_name='手机号码')),
                ('province', models.CharField(max_length=50, verbose_name='省份')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('area', models.CharField(max_length=50, verbose_name='地区')),
                ('brief', models.CharField(max_length=50, verbose_name='详细地址')),
                ('is_difault', models.BooleanField(default=False, verbose_name='默认地址')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
    ]
