# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-29 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harvestaddress',
            old_name='area',
            new_name='harea',
        ),
        migrations.RenameField(
            model_name='harvestaddress',
            old_name='province',
            new_name='hcity',
        ),
        migrations.RenameField(
            model_name='harvestaddress',
            old_name='city',
            new_name='hproper',
        ),
    ]
