# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-27 13:07
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('title', models.CharField(max_length=200, verbose_name='活动名称')),
                ('activity_image', models.ImageField(upload_to='activity/%Y%m/%d', verbose_name='活动图片地址')),
                ('url', models.URLField(verbose_name='活动url地址')),
            ],
            options={
                'verbose_name': '活动管理',
                'verbose_name_plural': '活动管理',
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='ActivityZoneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('title', models.CharField(max_length=200, verbose_name='活动专区名')),
                ('brief', models.CharField(blank=True, max_length=200, null=True, verbose_name='活动专区的简介')),
                ('order', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('is_on_sale', models.BooleanField(choices=[(True, '上架'), (False, '下架')], default=0, verbose_name='上否上线')),
            ],
            options={
                'verbose_name': '活动专区管理',
                'verbose_name_plural': '活动专区管理',
                'db_table': 'activity_zone',
            },
        ),
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('banner_name', models.CharField(max_length=200, verbose_name='轮播活动名')),
                ('banner_image', models.ImageField(upload_to='banner/%Y%m/%d', verbose_name='轮播图片地址')),
                ('order', models.SmallIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '首页轮播管理',
                'verbose_name_plural': '首页轮播管理',
                'db_table': 'banner',
            },
        ),
        migrations.CreateModel(
            name='GoodsAlbumModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('album_image', models.ImageField(upload_to='album', verbose_name='商品图片地址')),
            ],
            options={
                'verbose_name': '商品相册表',
                'verbose_name_plural': '商品相册表',
                'db_table': 'goods_categories',
            },
        ),
        migrations.CreateModel(
            name='GoodsClassifyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('class_name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('class_intro', models.CharField(max_length=50, null=True, verbose_name='分类简介')),
                ('order', models.SmallIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '商品分类表',
                'verbose_name_plural': '商品分类表',
                'db_table': 'goods_classify',
            },
        ),
        migrations.CreateModel(
            name='GoodsSkuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('goods_name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('goods_intro', models.TextField(verbose_name='商品信息')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='商品价格')),
                ('num', models.PositiveIntegerField(verbose_name='商品库存')),
                ('sell_num', models.PositiveIntegerField(verbose_name='商品销售量')),
                ('logo', models.ImageField(upload_to='logo/%Y%m', verbose_name='商品图片')),
                ('is_putaway', models.BooleanField(choices=[(True, '上架'), (False, '下架')], default=False, verbose_name='商品是否上架')),
                ('goods_cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.GoodsClassifyModel', verbose_name='商品分类')),
            ],
            options={
                'verbose_name': '商品SKU表',
                'verbose_name_plural': '商品SKU表',
                'db_table': 'goods_sku',
            },
        ),
        migrations.CreateModel(
            name='GoodsUnitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('unit_name', models.CharField(max_length=50, verbose_name='单位名称')),
            ],
            options={
                'verbose_name': '商品单位表',
                'verbose_name_plural': '商品单位表',
                'db_table': 'goods_unit',
            },
        ),
        migrations.CreateModel(
            name='SpuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('spu_name', models.CharField(max_length=50, verbose_name='商品spu名称')),
                ('spu_desc', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='商品spu描述')),
            ],
            options={
                'verbose_name': '商品SPU表',
                'verbose_name_plural': '商品SPU表',
                'db_table': 'goods_spu',
            },
        ),
        migrations.AddField(
            model_name='goodsskumodel',
            name='goods_spu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.SpuModel', verbose_name='商品spu分类'),
        ),
        migrations.AddField(
            model_name='goodsskumodel',
            name='unitinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.GoodsUnitModel', verbose_name='商品单位'),
        ),
        migrations.AddField(
            model_name='goodsalbummodel',
            name='album_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.GoodsSkuModel', verbose_name='商品sku的ID'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='banner_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.GoodsSkuModel', verbose_name='商品sku'),
        ),
        migrations.AddField(
            model_name='activityzonemodel',
            name='goods_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.GoodsSkuModel', verbose_name='商品'),
        ),
    ]
