# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsskumodel',
            name='is_putaway',
            field=models.BooleanField(choices=[(True, '上架'), (False, '下架')], default=False, verbose_name='商品是否上架'),
        ),
        migrations.AlterField(
            model_name='goodsskumodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='商品价格'),
        ),
    ]
