# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_auto_20190123_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('title', models.CharField(max_length=200, verbose_name='活动名称')),
                ('activity_image', models.ImageField(upload_to='activity/%Y%m/%d', verbose_name='活动图片地址')),
                ('url', models.URLField(verbose_name='活动url地址')),
            ],
            options={
                'verbose_name': '活动管理',
                'verbose_name_plural': '活动管理',
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='ActivityZoneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('title', models.CharField(max_length=200, verbose_name='活动专区名')),
                ('brief', models.CharField(blank=True, max_length=200, null=True, verbose_name='活动专区的简介')),
                ('order', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('is_on_sale', models.BooleanField(choices=[(True, '上架'), (False, '下架')], default=0, verbose_name='上否上线')),
                ('goods_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.GoodsSkuModel', verbose_name='商品')),
            ],
            options={
                'verbose_name': '活动专区管理',
                'verbose_name_plural': '活动专区管理',
                'db_table': 'activity_zone',
            },
        ),
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('banner_name', models.CharField(max_length=200, verbose_name='轮播活动名')),
                ('banner_image', models.ImageField(upload_to='banner/%Y%m/%d', verbose_name='轮播图片地址')),
                ('order', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('banner_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.GoodsSkuModel', verbose_name='商品sku')),
            ],
            options={
                'verbose_name': '首页轮播管理',
                'verbose_name_plural': '首页轮播管理',
                'db_table': 'banner',
            },
        ),
    ]
