# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-24 09:44
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0003_activitymodel_activityzonemodel_bannermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsclassifymodel',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='spumodel',
            name='spu_desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='商品spu描述'),
        ),
    ]
